spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul

    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true

    thymeleaf:
      cache: false

  mvc:
    static-path-pattern: /static/**

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
    ssl:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 1000
          starttls:
            enable: true

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}