name: Deploy Application

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # 4. Build with Gradle (skip tests)
      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      # 5. Upload JAR file as artifact
      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-application
          path: build/libs/Maching-0.0.1-SNAPSHOT.jar

      # 6. Get GitHub Actions IP
      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      # 7. Set environment variables
      - name: Set environment variables
        run: |
          echo "AWS_DEFAULT_REGION=ap-northeast-2" >> $GITHUB_ENV
          echo "AWS_SG_NAME=launch-wizard-2" >> $GITHUB_ENV

      # 8. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 9. Add GitHub Actions IP to Security Group
      - name: Add GitHub Actions IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-name ${{ env.AWS_SG_NAME }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      # 10. Deploy to AWS EC2
      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: build/libs/Maching-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/maple_matching/Maching-0.0.1-SNAPSHOT.jar

      # 11. Restart application on EC2
      - name: Restart application on EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            ps -ef | grep Maching-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9 || true
            nohup java -jar /home/ubuntu/maple_matching/Maching-0.0.1-SNAPSHOT.jar > /home/ubuntu/maple_matching/app.log 2>&1 &


      # 12. Remove GitHub Actions IP from Security Group
      - name: Remove GitHub Actions IP from Security Group
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-name ${{ env.AWS_SG_NAME }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2